### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by Domosed-gamin** [jhhuang7/Bark#1]
Hi. I compiled your game. But I no idea how launch it. Please tell me what write in terminal to play with AI? And please add manual about in-game control. Thank you.

**Comment by jhhuang7** [comment]
Hi @Domosed-gamin, sorry for the confusion. I have added game instructions to README.md which should have all the information you need to play the game. Please don't hesitate to let me know if you have any other issues. Have fun playing!
